clone:
  git:
    image: jakwuh/drone-git

pipeline:
  publish:
    image: plugins/docker
    repo: registry.thegraveyard.org/ced-pwned-systems
    dockerfile: Dockerfile
    registry: registry.thegraveyard.org
    secrets: [docker_username, docker_password]
    when:
      branch: master
